name: github-ci

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
      - uses: php-actions/phpunit@v3
      - with:
          php_extensions: xdebug
          configuration: phpunit.xml.dist
