name: linting

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - run: composer lint