.linting:
  image: thecodingmachine/php:8.0-v4-cli
  stage: lint
  only:
    refs:
      - merge_requests

lint-php-rector:
  extends: .linting
  script:
    - composer install --classmap-authoritative
    - composer lint:rector

lint-php-stan:
  extends: .linting
  script:
    - composer install --classmap-authoritative
    - composer lint:stan:gitlab
  artifacts:
    reports:
      codequality: phpstan.report.json

lint-php-cs-fixer:
  extends: .linting
  script:
    - composer install --classmap-authoritative
    - composer lint:csfixer:gitlab
  artifacts:
    reports:
      codequality: phpcsfixer.report.json

lint-php-parallel-lint:
  extends: .linting
  script:
    - composer install --classmap-authoritative
    - composer lint:parallel